version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    restart: unless-stopped
    environment:
      - APP_PORT
    tty: true
    stdin_open: true
    command: "python start.py"
